### ISSUE TITLE
Problema com a Splash Screen

### ISSUE THREAD

**Issue by jsericksk** [zLuCaS2K/MyTask#1]
A Splash Screen está com um pequeno erro ao ser exibida. Acredito que o problema seja o tema da MainActivity no AndroidManifest. A tag **application** está usando o tema da Splash Screen, **Theme.MyTaskSplash**, mas a MainActivity está com o tema padrão, **Theme.MyTask**.

Demonstração:

![demo](https://user-images.githubusercontent.com/36176569/169439311-4a100bbf-e775-48a1-8e54-b2512c580c09.gif)

**Comment by zLuCaS2K** [comment]
Corrigido no Commit e116b48
